// ========== 常量定义 ==========
export const CONSTANTS = {
  // 时间相关 (毫秒)
  TIME: {
    MS_PER_SECOND: 1000,
    SEEK_DEBOUNCE_MS: 50,
    RAF_THROTTLE_MS: 200,
    TIME_UPDATE_THROTTLE_MS: 100,
    REACT_UPDATE_THROTTLE_MS: 250,
    SWITCH_DEBOUNCE_MS: 100,
    PRELOAD_THRESHOLD_MS: 2000,
    PROGRESS_UPDATE_THRESHOLD_PERCENT: 1.0,
    TIME_GAP_TOLERANCE_MS: 50,
    VIDEO_SWITCH_THRESHOLD_MS: 50,
    MAX_SWITCH_WAIT_FRAMES: 2,
    SOFT_PAUSE_DURATION_MS: 100,
  },
  // WebSocket 相关
  WS: {
    MAX_RETRIES: 5,
    BASE_RECONNECT_DELAY_MS: 1000,
    MAX_RECONNECT_DELAY_MS: 10000,
    HEARTBEAT_INTERVAL_MS: 30000,
  },
  // 历史记录
  HISTORY: {
    MAX_SIZE: 50,
  },
  // 视频相关
  VIDEO: {
    READY_STATE_FUTURE_DATA: 3,
    READY_STATE_CURRENT_DATA: 2,
    MIN_VOLUME: 0.01,
    MAX_VOLUME: 1,
  },
  // UI 相关
  UI: {
    TOOLBAR_BUTTON_WIDTH: 160,
    TOOLBAR_OFFSET_Y: 45,
    MODAL_Z_INDEX: 2147483647,
    SCROLLBAR_WIDTH: 6,
  },
  // 进度相关
  PROGRESS: {
    MIN_PERCENT: 0,
    MAX_PERCENT: 100,
  },
} as const;
